routes/admin.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use Illuminate\Routing\Router;

Route::prefix("admin")->name("admin.")->namespace('Admin')->group(function(){
    Route::middleware(['guest:admin','PreventBackHistory'])->group(function(){
        Route::view('/login','dashboard.admin.login')->name('login');
        Route::view('/hello','dashboard.admin.hello')->name('hello');
        Route::post('/check',[AdminController::class,'check'])->name('check');
    });

    Route::middleware(['auth:admin','PreventBackHistory'])->group(function(){
        // Route::middleware(['role:admin'])->group(function (Router $router) {
        // Route::view('/home','dashboard.admin.home')->name('home');
        // });
        Route::view('/home','dashboard.admin.home')->name('home');
        Route::post('/logout',[AdminController::class,'logout'])->name('logout');
        Route::view('/info','dashboard.admin.info')->name('info');
    });
});

?>

routes/user.php
<?php
use Illuminate\Support\Facades\Route;
use App\HTTP\Controllers\User\UserController;

Route::prefix("user")->name("user.")->group(function(){
    Route::middleware(['guest:web','PreventBackHistory'])->group(function(){
        Route::view('/login','dashboard.user.login')->name('login');
        Route::post('/check',[UserController::class,'check'])->name('check');
        Route::view('/register','dashboard.user.register')->name('register');
        Route::view('/hello','dashboard.user.hello')->name('hello');
        Route::post('/create',[UserController::class,'create'])->name('create');
    });
    Route::middleware(['auth:web','PreventBackHistory'])->group(function(){
        Route::view('/home','dashboard.user.home')->name('home');
        Route::post('/logout',[UserController::class,'logout'])->name('logout');
        Route::view('/info','dashboard.user.info')->name('info');
    });
});

?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use GuzzleHttp\Promise\Create;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/index',[AdminController::class,'index'])->name('index');

//Prevent backtrack to login page after loggedout and move to welome page, make backtrack to thedash
Route::middleware(['middleware'=>'PreventBackHistory'])->group(function(){
    Auth::routes();
});

// Route::get('/user/home',function(){
//  return view('auth.login');
// });
// Route::middleware(['AccessToHome'])->group(function(){
//     Route::view('user/home','dashboard.user.home')->name('user.home');
//     Route::view('admin/home','dashboard.admin.home')->name('admin.home');
// });

?>

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'confirmPassword'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    function create(Request $request){
      $rules=[
         "name"=>"required|min:4",
         "email"=>"required|email|unique:users,email",
         "password"=>"required|min:5|max:30",
         "confirmPassword"=>"required|same:password|min:5|max:30",
     ];
     $this->validate($request,$rules);
     //dd($validate);
             $create=User::create([
            'name'=> $request->name,
            'email'=> $request->email,
            'password' => Hash::make($request['password']),
            'confirmPassword' => Hash::make($request->get('password'))
         ]);
        //  dd($create);
             if($create)
                 return redirect()->route('user.home')->with("success","User succussfully Creates.");
             else
                 return redirect()->back()->with("fail","Try to Create this User Again.");

}
function check(Request $request){
   $this->validate(
   $request,
   ["email"=>"required|email|exists:users,email","password"=>"required|min:5|max:30"],
   ['email.exists'=>'This Email Does not Exist in Users Table']
   );
    $cerds = $request->only('email','password');
    if( Auth::guard('web')->attempt($cerds) ){
        return redirect()->route('user.home')->with('success','correct credentails');
    }else{
        return redirect()->back()->with('fail','incorrect credentails Because This Email Exists in Users Table but does not correspond with entered password');//go to the same page [dashboard.user.register]
    }
}
function logout(){
    $name=Auth::guard('web')->user()->name;
    Auth::guard('web')->logout();
    //dd(Auth::user()->name);//UnKnown After logout
    //Auth::login(auth()->user());
    return redirect("/")->with("Bye","Bye ".$name);
}
};

resources/views/dashboard/user/hello.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
</head>
<body>
    @if(session('success'))
    <div class="alert alert-success">
        <strong>{{session('success')}}</strong>
    </div>
    @endif
    <div class="card">
        <h5 class="card-header">Hello User</h5>
    </div>
</body>
</html>

resources/views/dashboard/user/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
</head>
<body>
    @if(session('success'))
    <div class="alert alert-success">
        <strong>{{session('success')}}</strong>
    </div>
    @endif
    <div class="card">
        <h5 class="card-header">User Home</h5>
        <div class="card-body">
          @if(auth()->guard('web'))
            <h5 class="card-title"><b>Name :</b>{{auth()->guard('web')->user()->name}}</h5>
            <h5 class="card-title"><b>Email :</b>{{Auth::guard('web')->user()->email}}</h5>
          @elseif(auth()->guard('admin'))
            <h5 class="card-title"><b>Name :</b>{{auth()->guard('admin')->user()->name}}</h5>
            <h5 class="card-title"><b>Email :</b>{{Auth::guard('admin')->user()->email}}</h5>
          @endif
          <a class="btn btn-danger" href="{{route('user.logout')}}" onclick="event.preventDefault();document.getElementById('form-logout').submit()">LogOut</a>
          <form action="{{route('user.logout')}}" method="post" id="form-logout" class="d-none">@csrf</form>
        </div>
    </div>
</body>
</html>

resources/views/dashboard/user/info.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Info</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
</head>
<body>
    @if(session('success'))
    <div class="alert alert-success">
        <strong>{{session('success')}}</strong>
    </div>
    @endif
    <div class="card">
        <h5 class="card-header">Info For User</h5>
    </div>
</body>
</html>

resources/views/dashboard/user/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Login</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    {{-- <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}"> --}}
</head>
<body>
<div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <form action="{{route('user.check')}}" method="post">
            @csrf
        @if(Session::get('success'))
            <div class="alert alert-success">
                {{Session::get("success")}}
            </div>
        @elseif (Session::get('fail'))
            <div class="alert alert-success">
                {{Session::get("fail")}}
            </div>
        @endif
            <h2>User Login</h2>
            <div class="form-group">
                <label for="email"></label>
                <input type="text" name="email" id="" class="form-control" placeholder="Enter Your Email Here">
                @if ($errors->has('email'))
                 <span class="text-danger">@error('email'){{ $message }} @enderror</span>
                @endif
            </div>
            <div class="form-group">
                <label for="password"></label>
                <input type="text" name="password" id="" class="form-control" placeholder="Enter Your Password Here">
                @if ($errors->has('password'))
                 <span class="text-danger">{{ $errors->first('password') }}</span>
                @endif
            </div>
            <div class="form-group">
            <button type="submit" class="btn btn-primary">LogIn</button>
            </div>
            <br>
            <a href="{{route('user.register')}}">Create A New Account</a>
        </form>
    </div>
</div>
</body>
</html>

resources/views/dashboard/user/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Login</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    {{-- <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet"> --}}
    <style>
        form{
            margin-top: 79px;
        }
        .form-control{
            margin: 15px;
        }
        label{
            margin-left: 15px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <form action="{{ route('user.create') }}" method="post">
            @csrf
            @if (Session::get('fail'))
                <div class="alert alert-success">
                    {{Session::flash("fail")}}
                    {{session('fail')}}
                </div>
            @endif
            <h2>User Registeration</h2>
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="Enter Your Full-Name Here">
                <span class="text-danger">@error('name') {{$message}} @enderror</span>
            </div>
            <div class="form-group">
                <label for="email">email</label>
                <input type="text" name="email" value="{{ old('email') }}" class="form-control" placeholder="Enter Your Email Here">
                {{-- @if ($errors->has('email'))
                 <span class="text-danger">{{ $errors->first('email') }}</span>
                @endif --}}
                <span class="text-danger">@error('email') {{$message}} @enderror</span>
            </div>
            <div class="form-group">
                <label for="password">password</label>
                <input type="text" name="password" value="{{ old('password') }}" class="form-control" placeholder="Enter Your Password Here">
                <span class="text-danger">@error('password') {{$message}} @enderror</span>
            </div>
            <div class="form-group">
                <label for="confirmPassword">Confirm Password</label>
                <input type="text" name="confirmPassword" value="{{ old('confirmPassword') }}" class="form-control" placeholder="Please Confirm The Password Here">
                <span class="text-danger">@error('confirmPassword') {{$message}} @enderror</span>
            </div>
            <div class="form-group">
            <button type="submit" class="btn btn-primary">Register</button>
            </div>
            <br>
            <a href="{{route('user.login')}}">I Already Have An Account</a>
            @if(Session::get('success'))
            <div class="alert alert-success">
                {{Session::get("success")}}
            </div>
        @elseif (Session::get('fail'))
            <div class="alert alert-success">
                {{Session::get("fail")}}
            </div>
        @endif
        </form>
    </div>
</div>
</body>
</html>