routes/admin.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use Illuminate\Routing\Router;

Route::prefix("admin")->name("admin.")->namespace('Admin')->group(function(){
    Route::middleware(['guest:admin','PreventBackHistory'])->group(function(){
        Route::view('/login','dashboard.admin.login')->name('login');
        Route::view('/hello','dashboard.admin.hello')->name('hello');
        Route::post('/check',[AdminController::class,'check'])->name('check');
    });

    Route::middleware(['auth:admin','PreventBackHistory'])->group(function(){
        // Route::middleware(['role:admin'])->group(function (Router $router) {
        // Route::view('/home','dashboard.admin.home')->name('home');
        // });
        Route::view('/home','dashboard.admin.home')->name('home');
        Route::post('/logout',[AdminController::class,'logout'])->name('logout');
        Route::view('/info','dashboard.admin.info')->name('info');
    });
});

?>

routes/user.php
<?php
use Illuminate\Support\Facades\Route;
use App\HTTP\Controllers\User\UserController;

Route::prefix("user")->name("user.")->group(function(){
    Route::middleware(['guest:web','PreventBackHistory'])->group(function(){
        Route::view('/login','dashboard.user.login')->name('login');
        Route::post('/check',[UserController::class,'check'])->name('check');
        Route::view('/register','dashboard.user.register')->name('register');
        Route::view('/hello','dashboard.user.hello')->name('hello');
        Route::post('/create',[UserController::class,'create'])->name('create');
    });
    Route::middleware(['auth:web','PreventBackHistory'])->group(function(){
        Route::view('/home','dashboard.user.home')->name('home');
        Route::post('/logout',[UserController::class,'logout'])->name('logout');
        Route::view('/info','dashboard.user.info')->name('info');
    });
});

?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use GuzzleHttp\Promise\Create;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/index',[AdminController::class,'index'])->name('index');

//Prevent backtrack to login page after loggedout and move to welome page, make backtrack to thedash
Route::middleware(['middleware'=>'PreventBackHistory'])->group(function(){
    Auth::routes();
});

// Route::get('/user/home',function(){
//  return view('auth.login');
// });
// Route::middleware(['AccessToHome'])->group(function(){
//     Route::view('user/home','dashboard.user.home')->name('user.home');
//     Route::view('admin/home','dashboard.admin.home')->name('admin.home');
// });

?>

resources/views/dashboard/admin/hello.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
</head>
<body>
    @if(session('success'))
    <div class="alert alert-success">
        <strong>{{session('success')}}</strong>
    </div>
    @endif
    <div class="card">
        <h5 class="card-header">Hello Admin</h5>
    </div>
</body>
</html>

resources/views/dashboard/admin/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
</head>
<body>
    @if(session('success'))
    <div class="alert alert-success">
        <strong>{{session('success')}}</strong>
    </div>
    @endif
    <div class="card">
        <h5 class="card-header">Admin Home</h5>
        <div class="card-body">
            {{-- @role('admin')
            <a href="/admin/users/1/edit">Edit</a>;
            @endrole --}}
          <h5 class="card-title"><b>Name :</b>{{auth()->guard('admin')->user()->name}}</h5>
          <h5 class="card-title"><b>Email :</b>{{Auth::guard('admin')->user()->email}}</h5>
          <h5 class="card-title"><b>Phone :</b>{{auth()->guard('admin')->user()->phone}}</h5>
          <a class="btn btn-danger" href="{{route('admin.logout')}}" onclick="event.preventDefault();document.getElementById('form-logout').submit()">LogOut</a>
          <form action="{{route('admin.logout')}}" method="post" id="form-logout" class="d-none">@csrf</form>
        </div>
    </div>
</body>
</html>

resources/views/dashboard/admin/info.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Info</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
</head>
<body>
    @if(session('success'))
    <div class="alert alert-success">
        <strong>{{session('success')}}</strong>
    </div>
    @endif
    <div class="card">
        <h5 class="card-header">Info For Admin</h5>
    </div>
</body>
</html>

resources/views/dashboard/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Admin Login</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    {{-- <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}"> --}}
</head>
<body class="bg-black" style="margin-top: 30px;">
<div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        @if (session('fail'))
            <div class="alert alert-success">
                {{Session::get("fail")}}
            </div>
        @endif
        <form action="{{route('admin.check')}}" method="post" autocomplete="false">
            @csrf
            <h2 class="text-white">Admin Login</h2>
            <div class="form-group">
                <label for="email"></label>
                <input type="email" name="email" id="" value="{{old('email')}}" class="form-control" placeholder="Enter Your Email Here">
                <span class="text-danger">@error('email'){{ $message }} @enderror</span>
            </div>
            <div class="form-group">
                <label for="password"></label>
                <input type="password" name="password" id="" value="{{old('password')}}" class="form-control" placeholder="Enter Your Password Here">
                <span class="text-danger">@error('password'){{$message}}@enderror</span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary mt-9">LogIn</button>
            </div>
            <br>
            {{-- <a href="{{route('user.register')}}">Create A New Account</a> --}}
        </form>
    </div>
</div>
</body>
</html>